version: '3.8'

services:
  app:
    build: .
    container_name: search_engine_app
    restart: unless-stopped
    expose:
      - 5009
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: search_engine_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge